// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p/types.proto

package p2p

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetAddress struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetAddress) Reset()         { *m = NetAddress{} }
func (m *NetAddress) String() string { return proto.CompactTextString(m) }
func (*NetAddress) ProtoMessage()    {}
func (*NetAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_046d1b81fed804bc, []int{0}
}

func (m *NetAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetAddress.Unmarshal(m, b)
}
func (m *NetAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetAddress.Marshal(b, m, deterministic)
}
func (m *NetAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetAddress.Merge(m, src)
}
func (m *NetAddress) XXX_Size() int {
	return xxx_messageInfo_NetAddress.Size(m)
}
func (m *NetAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NetAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NetAddress proto.InternalMessageInfo

func (m *NetAddress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NetAddress) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NetAddress) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ProtocolVersion struct {
	P2P                  uint64   `protobuf:"varint,1,opt,name=p2p,proto3" json:"p2p,omitempty"`
	Block                uint64   `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	App                  uint64   `protobuf:"varint,3,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtocolVersion) Reset()         { *m = ProtocolVersion{} }
func (m *ProtocolVersion) String() string { return proto.CompactTextString(m) }
func (*ProtocolVersion) ProtoMessage()    {}
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_046d1b81fed804bc, []int{1}
}

func (m *ProtocolVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolVersion.Unmarshal(m, b)
}
func (m *ProtocolVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolVersion.Marshal(b, m, deterministic)
}
func (m *ProtocolVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolVersion.Merge(m, src)
}
func (m *ProtocolVersion) XXX_Size() int {
	return xxx_messageInfo_ProtocolVersion.Size(m)
}
func (m *ProtocolVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolVersion proto.InternalMessageInfo

func (m *ProtocolVersion) GetP2P() uint64 {
	if m != nil {
		return m.P2P
	}
	return 0
}

func (m *ProtocolVersion) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *ProtocolVersion) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

type DefaultNodeInfo struct {
	ProtocolVersion      *ProtocolVersion      `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	DefaultNodeId        string                `protobuf:"bytes,2,opt,name=default_node_id,json=defaultNodeId,proto3" json:"default_node_id,omitempty"`
	ListenAddr           string                `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Network              string                `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Version              string                `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Channels             []byte                `protobuf:"bytes,6,opt,name=channels,proto3" json:"channels,omitempty"`
	Moniker              string                `protobuf:"bytes,7,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Other                *DefaultNodeInfoOther `protobuf:"bytes,8,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DefaultNodeInfo) Reset()         { *m = DefaultNodeInfo{} }
func (m *DefaultNodeInfo) String() string { return proto.CompactTextString(m) }
func (*DefaultNodeInfo) ProtoMessage()    {}
func (*DefaultNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_046d1b81fed804bc, []int{2}
}

func (m *DefaultNodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultNodeInfo.Unmarshal(m, b)
}
func (m *DefaultNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultNodeInfo.Marshal(b, m, deterministic)
}
func (m *DefaultNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultNodeInfo.Merge(m, src)
}
func (m *DefaultNodeInfo) XXX_Size() int {
	return xxx_messageInfo_DefaultNodeInfo.Size(m)
}
func (m *DefaultNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultNodeInfo proto.InternalMessageInfo

func (m *DefaultNodeInfo) GetProtocolVersion() *ProtocolVersion {
	if m != nil {
		return m.ProtocolVersion
	}
	return nil
}

func (m *DefaultNodeInfo) GetDefaultNodeId() string {
	if m != nil {
		return m.DefaultNodeId
	}
	return ""
}

func (m *DefaultNodeInfo) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *DefaultNodeInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *DefaultNodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DefaultNodeInfo) GetChannels() []byte {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *DefaultNodeInfo) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *DefaultNodeInfo) GetOther() *DefaultNodeInfoOther {
	if m != nil {
		return m.Other
	}
	return nil
}

type DefaultNodeInfoOther struct {
	TxIndex              string   `protobuf:"bytes,1,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	RpcAddress           string   `protobuf:"bytes,2,opt,name=rpc_address,json=rpcAddress,proto3" json:"rpc_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultNodeInfoOther) Reset()         { *m = DefaultNodeInfoOther{} }
func (m *DefaultNodeInfoOther) String() string { return proto.CompactTextString(m) }
func (*DefaultNodeInfoOther) ProtoMessage()    {}
func (*DefaultNodeInfoOther) Descriptor() ([]byte, []int) {
	return fileDescriptor_046d1b81fed804bc, []int{3}
}

func (m *DefaultNodeInfoOther) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultNodeInfoOther.Unmarshal(m, b)
}
func (m *DefaultNodeInfoOther) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultNodeInfoOther.Marshal(b, m, deterministic)
}
func (m *DefaultNodeInfoOther) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultNodeInfoOther.Merge(m, src)
}
func (m *DefaultNodeInfoOther) XXX_Size() int {
	return xxx_messageInfo_DefaultNodeInfoOther.Size(m)
}
func (m *DefaultNodeInfoOther) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultNodeInfoOther.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultNodeInfoOther proto.InternalMessageInfo

func (m *DefaultNodeInfoOther) GetTxIndex() string {
	if m != nil {
		return m.TxIndex
	}
	return ""
}

func (m *DefaultNodeInfoOther) GetRpcAddress() string {
	if m != nil {
		return m.RpcAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*NetAddress)(nil), "tendermint.p2p.NetAddress")
	proto.RegisterType((*ProtocolVersion)(nil), "tendermint.p2p.ProtocolVersion")
	proto.RegisterType((*DefaultNodeInfo)(nil), "tendermint.p2p.DefaultNodeInfo")
	proto.RegisterType((*DefaultNodeInfoOther)(nil), "tendermint.p2p.DefaultNodeInfoOther")
}

func init() { proto.RegisterFile("p2p/types.proto", fileDescriptor_046d1b81fed804bc) }

var fileDescriptor_046d1b81fed804bc = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x3d, 0x6f, 0xdb, 0x30,
	0x10, 0xad, 0x65, 0xf9, 0x23, 0xe7, 0x38, 0x4a, 0x09, 0xa3, 0x50, 0xb2, 0xc8, 0x30, 0x3a, 0x78,
	0xb2, 0x01, 0x75, 0xea, 0xd6, 0xba, 0x5e, 0xbc, 0xa4, 0x02, 0x51, 0x74, 0xe8, 0x22, 0xd8, 0xe2,
	0x25, 0x21, 0xac, 0x90, 0x07, 0x8a, 0x6d, 0xdd, 0x7f, 0xd8, 0x5f, 0xa1, 0xc1, 0x6b, 0xff, 0x44,
	0x21, 0x52, 0x29, 0x5c, 0x23, 0xdb, 0xbd, 0xfb, 0x7a, 0xef, 0x1e, 0x09, 0x11, 0xa5, 0xb4, 0xb4,
	0xbf, 0x08, 0xab, 0x05, 0x19, 0x6d, 0x35, 0xbb, 0xb2, 0xa8, 0x04, 0x9a, 0x27, 0xa9, 0xec, 0x82,
	0x52, 0xba, 0x9d, 0x3c, 0xe8, 0x07, 0xed, 0x4a, 0xcb, 0x26, 0xf2, 0x5d, 0xb3, 0x0c, 0xe0, 0x0e,
	0xed, 0x47, 0x21, 0x0c, 0x56, 0x15, 0x7b, 0x03, 0x81, 0x14, 0x71, 0x67, 0xda, 0x99, 0x5f, 0xac,
	0xfa, 0xc7, 0x3a, 0x09, 0x36, 0x6b, 0x1e, 0x48, 0xe1, 0xf2, 0x14, 0x07, 0x27, 0xf9, 0x8c, 0x07,
	0x92, 0x18, 0x83, 0x90, 0xb4, 0xb1, 0x71, 0x77, 0xda, 0x99, 0x8f, 0xb9, 0x8b, 0x67, 0x5f, 0x20,
	0xca, 0x9a, 0xd5, 0x85, 0x2e, 0xbf, 0xa2, 0xa9, 0xa4, 0x56, 0xec, 0x06, 0xba, 0x94, 0x92, 0xdb,
	0x1b, 0xae, 0x06, 0xc7, 0x3a, 0xe9, 0x66, 0x69, 0xc6, 0x9b, 0x1c, 0x9b, 0x40, 0x6f, 0x57, 0xea,
	0x62, 0xef, 0x96, 0x87, 0xdc, 0x03, 0x76, 0x0d, 0xdd, 0x2d, 0x91, 0x5b, 0x1b, 0xf2, 0x26, 0x9c,
	0xfd, 0x09, 0x20, 0x5a, 0xe3, 0xfd, 0xf6, 0x7b, 0x69, 0xef, 0xb4, 0xc0, 0x8d, 0xba, 0xd7, 0x2c,
	0x83, 0x6b, 0x6a, 0x99, 0xf2, 0x1f, 0x9e, 0xca, 0x71, 0x8c, 0xd2, 0x64, 0xf1, 0xff, 0xf1, 0x8b,
	0x33, 0x45, 0xab, 0xf0, 0x77, 0x9d, 0xbc, 0xe2, 0x11, 0x9d, 0x09, 0x7d, 0x0f, 0x91, 0xf0, 0x24,
	0xb9, 0xd2, 0x02, 0x73, 0x29, 0xda, 0xa3, 0x5f, 0x1f, 0xeb, 0x64, 0x7c, 0xca, 0xbf, 0xe6, 0x63,
	0x71, 0x02, 0x05, 0x4b, 0x60, 0x54, 0xca, 0xca, 0xa2, 0xca, 0xb7, 0x42, 0x18, 0x27, 0xfd, 0x82,
	0x83, 0x4f, 0x35, 0xf6, 0xb2, 0x18, 0x06, 0x0a, 0xed, 0x4f, 0x6d, 0xf6, 0x71, 0xe8, 0x8a, 0xcf,
	0xb0, 0xa9, 0x3c, 0xcb, 0xef, 0xf9, 0x4a, 0x0b, 0xd9, 0x2d, 0x0c, 0x8b, 0xc7, 0xad, 0x52, 0x58,
	0x56, 0x71, 0x7f, 0xda, 0x99, 0x5f, 0xf2, 0x7f, 0xb8, 0x99, 0x7a, 0xd2, 0x4a, 0xee, 0xd1, 0xc4,
	0x03, 0x3f, 0xd5, 0x42, 0xf6, 0x01, 0x7a, 0xda, 0x3e, 0xa2, 0x89, 0x87, 0xce, 0x8c, 0xb7, 0xe7,
	0x66, 0x9c, 0xf9, 0xf8, 0xb9, 0xe9, 0x6d, 0x1d, 0xf1, 0x83, 0xb3, 0x1d, 0x4c, 0x5e, 0x6a, 0x62,
	0x37, 0x30, 0xb4, 0x87, 0x5c, 0x2a, 0x81, 0x07, 0xff, 0x4b, 0xf8, 0xc0, 0x1e, 0x36, 0x0d, 0x64,
	0x4b, 0x18, 0x19, 0x2a, 0xdc, 0xf1, 0x58, 0x55, 0xad, 0x6d, 0x57, 0xc7, 0x3a, 0x01, 0x9e, 0x7d,
	0x6a, 0xff, 0x17, 0x07, 0x43, 0x45, 0x1b, 0xaf, 0x2e, 0xbf, 0x41, 0x51, 0x4a, 0x54, 0x76, 0x49,
	0x29, 0xed, 0xfa, 0xee, 0x29, 0xde, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x79, 0x30, 0x04, 0xa8,
	0xc7, 0x02, 0x00, 0x00,
}
