// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tmservice/service.proto

package tmservice

import (
	p2p "client/p2p"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetNodeInfoRequest is the request type for the Query/GetNodeInfo RPC method.
type GetNodeInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeInfoRequest) Reset()         { *m = GetNodeInfoRequest{} }
func (m *GetNodeInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeInfoRequest) ProtoMessage()    {}
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64dc1cae6946e1c5, []int{0}
}

func (m *GetNodeInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeInfoRequest.Unmarshal(m, b)
}
func (m *GetNodeInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeInfoRequest.Merge(m, src)
}
func (m *GetNodeInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeInfoRequest.Size(m)
}
func (m *GetNodeInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeInfoRequest proto.InternalMessageInfo

// GetNodeInfoResponse is the response type for the Query/GetNodeInfo RPC
// method.
type GetNodeInfoResponse struct {
	DefaultNodeInfo      *p2p.DefaultNodeInfo `protobuf:"bytes,1,opt,name=default_node_info,json=defaultNodeInfo,proto3" json:"default_node_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetNodeInfoResponse) Reset()         { *m = GetNodeInfoResponse{} }
func (m *GetNodeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeInfoResponse) ProtoMessage()    {}
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64dc1cae6946e1c5, []int{1}
}

func (m *GetNodeInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeInfoResponse.Unmarshal(m, b)
}
func (m *GetNodeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeInfoResponse.Merge(m, src)
}
func (m *GetNodeInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeInfoResponse.Size(m)
}
func (m *GetNodeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeInfoResponse proto.InternalMessageInfo

func (m *GetNodeInfoResponse) GetDefaultNodeInfo() *p2p.DefaultNodeInfo {
	if m != nil {
		return m.DefaultNodeInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*GetNodeInfoRequest)(nil), "cosmos.base.tendermint.vibeta1.GetNodeInfoRequest")
	proto.RegisterType((*GetNodeInfoResponse)(nil), "cosmos.base.tendermint.vibeta1.GetNodeInfoResponse")
}

func init() { proto.RegisterFile("tmservice/service.proto", fileDescriptor_64dc1cae6946e1c5) }

var fileDescriptor_64dc1cae6946e1c5 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4a, 0xc4, 0x30,
	0x14, 0x86, 0xa9, 0x0b, 0x85, 0xcc, 0x62, 0x30, 0x2a, 0x23, 0x83, 0xa8, 0x74, 0xa5, 0x08, 0x79,
	0xb4, 0x73, 0x03, 0x11, 0x44, 0x04, 0x17, 0xba, 0x73, 0x33, 0xa4, 0xed, 0x6b, 0x09, 0xb4, 0xef,
	0xc5, 0xe6, 0x4d, 0xc1, 0xad, 0x57, 0xf0, 0x14, 0x1e, 0xc0, 0x93, 0x78, 0x05, 0x0f, 0x22, 0x4e,
	0x87, 0x3a, 0x83, 0x20, 0xb8, 0x0a, 0xfc, 0xc9, 0x97, 0xfc, 0x5f, 0x9e, 0x9a, 0x48, 0x13, 0xb0,
	0xed, 0x5c, 0x8e, 0xb0, 0x5a, 0x8d, 0x6f, 0x59, 0x58, 0x1f, 0xe7, 0x1c, 0x1a, 0x0e, 0x26, 0xb3,
	0x01, 0x8d, 0x20, 0x15, 0xd8, 0x36, 0x8e, 0xc4, 0x74, 0x2e, 0x43, 0xb1, 0xc9, 0x74, 0xec, 0x53,
	0x0f, 0xf2, 0xec, 0x31, 0xf4, 0xc0, 0xf4, 0xa8, 0x62, 0xae, 0x6a, 0x04, 0xeb, 0x1d, 0x58, 0x22,
	0x16, 0x2b, 0x8e, 0x69, 0xb5, 0x1b, 0xef, 0x2b, 0x7d, 0x8d, 0x72, 0xc7, 0x05, 0xde, 0x50, 0xc9,
	0xf7, 0xf8, 0xb4, 0xc0, 0x20, 0x71, 0xa6, 0xf6, 0x36, 0xd2, 0xe0, 0x99, 0x02, 0xea, 0x5b, 0xb5,
	0x5b, 0x60, 0x69, 0x17, 0xb5, 0xcc, 0x89, 0x0b, 0x9c, 0x3b, 0x2a, 0xf9, 0x30, 0x3a, 0x8d, 0xce,
	0x46, 0xe9, 0xc9, 0x7a, 0x17, 0x9f, 0x7a, 0x73, 0xd5, 0x1f, 0x1c, 0xee, 0x18, 0x17, 0x9b, 0x41,
	0xfa, 0x1e, 0xa9, 0x9d, 0x87, 0x5e, 0x4d, 0xbf, 0x45, 0x6a, 0xb4, 0xf6, 0xa0, 0x4e, 0xcd, 0xdf,
	0x96, 0xe6, 0x77, 0xe7, 0xe9, 0xec, 0x5f, 0x4c, 0x6f, 0x14, 0x27, 0x2f, 0x1f, 0x9f, 0xaf, 0x5b,
	0x17, 0xfa, 0x1c, 0x7a, 0x18, 0xbe, 0x61, 0xf8, 0x81, 0xa1, 0x4b, 0x96, 0x30, 0x0c, 0xbe, 0x97,
	0x93, 0xc7, 0x83, 0xbc, 0x76, 0x48, 0x02, 0x55, 0xeb, 0x73, 0x18, 0xe6, 0x94, 0x6d, 0x2f, 0x7f,
	0x74, 0xf6, 0x15, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x2c, 0xbe, 0x68, 0xbb, 0x01, 0x00, 0x00,
}
